<a href="https://colab.research.google.com/github/mioyn/AdvDataProg/blob/main/advance_prog_cls_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Intro:

In [ ]:
name = input("Enter name: ")
number = int(input("Find square of number: "))
sqr = number ** 2
print(f"Hello {name}!!")
print(f"square of {number} is {sqr}!!")

Enter name: Midhun
Find square of number: 5
Hello Midhun!!
square of 5 is 25!!


In [ ]:
"TEST".lower()

'test'

In [ ]:
"HEST".replace("H", "T")

'TEST'

In [ ]:
" TEST ".strip()

'TEST'

In [ ]:
" TEST ".lstrip()

'TEST '

In [ ]:
" TEST ".rstrip()

' TEST'

In [ ]:
num = [0,1,2,3,4,5,6,7]
print(num[:2])

[0, 1]


In [ ]:
num = [1,2,3,4]
num.pop(1) #remove index 1
print(num)
num = [1,2,3,4]
num.remove(1) # remove value 1
print(num)

[1, 3, 4]
[2, 3, 4]


In [ ]:
num = [4,1,2,3]
num.sort()
print(num)

[1, 2, 3, 4]


In [ ]:
num = [4,1,2,3]
num.sort(reverse=True)
print(num)

[4, 3, 2, 1]


In [ ]:
# prompt: code to update a tuple

# Python tuples are immutable, meaning their elements cannot be changed after creation.
# To "update" a tuple, you need to create a new tuple based on the existing one.

my_tuple = (1, 2, 3, 4, 5)

# Example: Changing an element at a specific index (conceptually)
index_to_change = 2
new_value = 10

# Create a new tuple with the desired change
updated_tuple = my_tuple[:index_to_change] + (new_value,) + my_tuple[index_to_change+1:]

print(f"Original tuple: {my_tuple}")
print(f"Updated tuple: {updated_tuple}")

# Example: Adding an element to a tuple
element_to_add = 6
added_tuple = my_tuple + (element_to_add,)

print(f"Tuple with added element: {added_tuple}")

# Example: Removing an element from a tuple (conceptually)
element_to_remove = 3
removed_tuple = tuple(x for x in my_tuple if x != element_to_remove)

print(f"Tuple with removed element: {removed_tuple}")

Original tuple: (1, 2, 3, 4, 5)
Updated tuple: (1, 2, 10, 4, 5)
Tuple with added element: (1, 2, 3, 4, 5, 6)
Tuple with removed element: (1, 2, 4, 5)


In [ ]:
a = {1,2,3,4}
a.add(6)
a

{1, 2, 3, 4, 6}

In [ ]:
a.remove(4)  # remove value 4 ; use discard function to
a

{1, 2, 3, 6}

In [ ]:
a.pop()
a

{2, 3, 4, 6}

In [ ]:
person = {"name": "John", "age": 30, "city": "New York"}
person["name"]
person.get("name")
person.pop("age") # remove key age
person

{'name': 'John', 'city': 'New York'}

In [ ]:
fruits = ["apple", "banana", "cherry"]
fruits.append("orange")
print(fruits)

['apple', 'banana', 'cherry', 'orange']


In [ ]:
book = {"title": "Python", "author": "Eric", "year": 2015}
print(book.get("author"))

Eric


In [ ]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}
union_set = set1.union(set2)
print(union_set)

{1, 2, 3, 4, 5}


In [ ]:
for i in fruits:
    print(i)

apple
banana
cherry
orange


In [ ]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(1, 20, 3):
    print(i)

1
4
7
10
13
16
19


In [ ]:
# terinary condition example
message = "Hello" if 5 > 3 else "Goodbye"
print(message)

Hello


In [ ]:
for i in range(1, 21):
  if i % 3 == 0:
    continue
  print(i)



1
2
4
5
7
8
10
11
13
14
16
17
19
20


In [ ]:
sum=0
i=0
while i < 10:
  sum = sum + i
  i = i+1

print(sum)

45


# Library for ML

## numpy


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(np.mean(arr))

mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat.shape)

arr1 = np.array([[1, 2, 3], [4, 5,6]])
print(arr1)
print(arr1.dtype)
print(arr1.ndim)

[1 2 3 4 5]
3.0
(2, 3)
[[1 2 3]
 [4 5 6]]
int64
2


In [ ]:
arr2 = np.arange(9)
print(arr2)
arr2 = arr2.reshape(3,3)
print(arr2)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
arr3 = np.zeros(10)
arr4 = np.ones(10)
print(arr3)
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
arr = np.random.rand(3,3)
print(arr)

arr = np.random.randint(1, 10, size=(3, 3))
print(arr)

[[0.29655541 0.51385796 0.84134854]
 [0.73139192 0.24409288 0.25876987]
 [0.67537538 0.5807419  0.76121779]]
[[3 3 7]
 [8 1 9]
 [4 1 3]]


In [ ]:
arr1 = np.array([5,8,3,7,2,9])
print(arr1.max())
print(arr1.min())
print(arr1.argmin())

9
2
4


## Pandas


In [ ]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Age': [25, 30, 35]}

df = pd.DataFrame(data)
df

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df['City']= ['New York', 'San Francisco', 'Los Angeles']
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes


In [ ]:
df.describe()

Age
count  0.0
mean   NaN
std    NaN
min    NaN
25%    NaN
50%    NaN
75%    NaN
max    NaN

In [ ]:
type(df['Age'])

pandas.core.series.Series

In [ ]:
df.loc[df['Name'] == 'Bob', 'City']="Bang"
df

Name  Age         City
0    Alice   25     New York
1      Bob   30         Bang
2  Charlie   35  Los Angeles

In [ ]:
df.drop(columns=['City'], inplace=True)
df

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df1 = df[df['Age']> 27]
df1

Empty DataFrame
Columns: [Name, Age, City]
Index: []

In [ ]:
df1 = df[df['Name'] == 'Alice']
df1

Name  Age
0  Alice   25

In [ ]:
# group df by city adn calculate the average age in each group

df.groupby('City')['Age'].mean()

City
Los Angeles      35.0
New York         25.0
San Francisco    30.0
Name: Age, dtype: float64

In [ ]:
df.sort_values(by='Age', ascending=False)

Name  Age           City
2  Charlie   35    Los Angeles
1      Bob   30  San Francisco
0    Alice   25       New York

## Scikit learn


In [ ]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive



In [ ]:
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful

In [ ]:

df=pd.read_csv('/content/drive/MyDrive/datasets/high-school.csv')